actions:
  goto_r1:
    attr:
      pose:
      - [2.5, 1.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r10:
    attr:
      pose:
      - [2.5, 4.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r11:
    attr:
      pose:
      - [3.5, 4.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r12:
    attr:
      pose:
      - [4.5, 4.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r2:
    attr:
      pose:
      - [3.5, 1.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r3:
    attr:
      pose:
      - [4.5, 1.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r4:
    attr:
      pose:
      - [2.5, 2.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r5:
    attr:
      pose:
      - [3.5, 2.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r6:
    attr:
      pose:
      - [4.5, 2.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r7:
    attr:
      pose:
      - [2.5, 3.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r8:
    attr:
      pose:
      - [3.5, 3.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_r9:
    attr:
      pose:
      - [4.5, 3.5, 0]
      - [0, 0, 0, 1]
    type: move
    weight: 10
  goto_s0:
    attr:
      pose:
      - [2.0, 2.2, 0]
      - [0.0, 0.0, 0.0, 1.0]
    type: move
    weight: 10
state_dim: [2d_pose_region]
state_models:
  2d_pose_region:
    initial: ''
    nodes:
      r1:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [2.5, 1.5]
          - [0]
          type: square
        connected_to: {r2: goto_r2, r4: goto_r4}
      r10:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [2.5, 4.5]
          - [0]
          type: square
        connected_to: {r11: goto_r11, r7: goto_r7, r9: goto_r9}
      r11:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [3.5, 4.5]
          - [0]
          type: square
        connected_to: {r10: goto_r10, r12: goto_r12, r8: goto_r8}
      r12:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [4.5, 4.5]
          - [0]
          type: square
        connected_to: {r11: goto_r11, r9: goto_r9}
      r2:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [3.5, 1.5]
          - [0]
          type: square
        connected_to: {r1: goto_r1, r3: goto_r3, r5: goto_r5}
      r3:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [4.5, 1.5]
          - [0]
          type: square
        connected_to: {r2: goto_r2, r4: goto_r4, r6: goto_r6}
      r4:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [2.5, 2.5]
          - [0]
          type: square
        connected_to: {r1: goto_r1, r3: goto_r3, r5: goto_r5, r7: goto_r7, s0: goto_s0}
      r5:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [3.5, 2.5]
          - [0]
          type: square
        connected_to: {r2: goto_r2, r4: goto_r4, r6: goto_r6, r8: goto_r8}
      r6:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [4.5, 2.5]
          - [0]
          type: square
        connected_to: {r3: goto_r3, r5: goto_r5, r7: goto_r7, r9: goto_r9}
      r7:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [2.5, 3.5]
          - [0]
          type: square
        connected_to: {r10: goto_r10, r4: goto_r4, r6: goto_r6, r8: goto_r8}
      r8:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [3.5, 3.5]
          - [0]
          type: square
        connected_to: {r11: goto_r11, r5: goto_r5, r7: goto_r7, r9: goto_r9}
      r9:
        attr:
          hysteresis: 0.05
          length: 1.0
          pose:
          - [4.5, 3.5]
          - [0]
          type: square
        connected_to: {r10: goto_r10, r12: goto_r12, r6: goto_r6, r8: goto_r8}
      s0:
        attr:
          angle_hysteresis: 0.1
          angle_tolerance: 0.2
          dist_hysteresis: 0.2
          pose:
          - [2.0, 2.2]
          - [0.0]
          radius: 0.2
          type: station
        connected_to: {r4: goto_r4}
    ts_type: 2d_pose_region
