# Service for planning given a task

# Task is expressed as a hard task LTL formula and soft task LTL formula
string hard_task
string soft_task

---

# Returns true if planning was successful, false otherwise
bool success
