# Service message for trap checking in a LTL automaton

# Transition system state to be tested for trap
TransitionSystemState ts_state

---

# Returns false if state is not connected to agent current
# state and therefor cannot be tested for trap
bool is_connected

# Returns true if check state is a trap, false otherwises
bool is_trap

