# TS definitions are to be interpreted by the agent node. The LTL core planner only uses the node names, connections, weights, and action names to build its automaton.
#
# Possible TS types:
#   3d_pose_region (3D pose [[x,y,z], [x,y,z,w]] with quaternion orientation)
#   2d_pose_region (2D pose [[x,y], phi] with euler angle orientation)
#   3d_point_region (3D point [x, y, z] without orientation)
#   2d_point_region (2D point [x, y] without orientation)
#   turtlebot_load

#state_dim: ["2d_pose_region", "turtlebot_load"]
state_dim: ["2d_pose_region", "A1_load"]
state_models:
  2d_pose_region:
    ts_type: "2d_pose_region"
    initial: "r2"
    nodes:
      r1:
        attr:
          type: "square"
          pose: [[2,0], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          r1: "stay"
          c1: "goto_c1"
      r2:
        attr:
          type: "square"
          pose: [[1,7], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          r2: "stay"
          c2: "goto_c2"
      r3:
        attr:
          type: "square"
          pose: [[-1,12.4], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          r3: "stay"
          c3: "goto_c3"

      r4:
        attr:
          type: "square"
          pose: [ [ -9,-1 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r4: "stay"
          c1: "goto_c1"

      r5:
        attr:
          type: "square"
          pose: [ [ -8,5.5 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r5: "stay"
          c2: "goto_c2"
      r6:
        attr:
          type: "square"
          pose: [ [ -9,11 ], [ 0 ] ]
          length: 1.5
          hysteresis: 0.05
        connected_to:
          r6: "stay"
          c3: "goto_c3"
      r7:
        attr:
          type: "square"
          pose: [ [ -16,23 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r7: "stay"
          c7: "goto_c7"
      r8:
        attr:
          type: "square"
          pose: [ [ -16,31 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r8: "stay"
          c8: "goto_c8"
          c9: "goto_c9"
      r9:
        attr:
          type: "square"
          pose: [ [ -27,23 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r9: "stay"
          c7: "goto_c7"
      r10:
        attr:
          type: "square"
          pose: [ [ -27,31 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          r10: "stay"
          c8: "goto_c8"
          c9: "goto_c9"
      c1:
        attr:
          type: "square"
          pose: [ [ -4,1.2 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c1: "stay"
          r1: "goto_r1"
          c2: "goto_c2"
          r4: "goto_r4"
      c2:
        attr:
          type: "square"
          pose: [ [ -4,7.37 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c1: "goto_c1"
          c2: "stay"
          c3: "goto_c3"
          r2: "goto_r2"
          r5: "goto_r5"
      c3:
        attr:
          type: "square"
          pose: [ [ -4,13.3 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c2: "goto_c2"
          c3: "stay"
          c4: "goto_c4"
          r3: "goto_r3"
          r6: "goto_r6"
      c4:
        attr:
          type: "square"
          pose: [ [ -4.8,17.7 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c3: "goto_c3"
          c4: "stay"
          c5: "goto_c5"
      c5:
        attr:
          type: "square"
          pose: [ [ -12.5,17.7 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c4: "goto_c4"
          c5: "stay"
          c6: "goto_c6"
      c6:
        attr:
          type: "square"
          pose: [ [ -22,17.7 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c5: "goto_c5"
          c6: "stay"
          c7: "goto_c7"
      c7:
        attr:
          type: "square"
          pose: [ [ -22,25.3 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c6: "goto_c6"
          c7: "stay"
          c8: "goto_c8"
          r7: "goto_r7"
          r9: "goto_r9"
      c8:
        attr:
          type: "square"
          pose: [ [ -22,27.7 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c7: "goto_c7"
          c8: "stay"
          c9: "goto_c9"
          r8: "goto_r8"
          r10: "goto_r10"
      c9:
        attr:
          type: "square"
          pose: [ [ -22,35.7 ], [ 0 ] ]
          length: 1
          hysteresis: 0.05
        connected_to:
          c8: "goto_c8"
          c9: "stay"
          r8: "goto_r8"
          r10: "goto_r10"
  A1_load:
    ts_type: "A1_load"
    initial: "unloaded"
    nodes:
      unloaded:
        connected_to:
          loaded: "pick"
      loaded:
        connected_to:
          unloaded: "drop"

actions:
  goto_r1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r1
      pose: [[2,0,0], [0,0,0,1]]
  goto_r2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r2
      pose: [[1,7,0], [0,0,0,1]]
  goto_r3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r3
      pose: [[-1,12.4,0], [0,0,0,1]]
  goto_r4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r4
      pose: [ [ -9,-1,0 ], [ 0,0,0,1 ] ]
  goto_r5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r5
      pose: [ [ -8,5.5,0 ], [ 0,0,0,1 ] ]
  goto_r6:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r6
      pose: [ [ -9,11,0 ], [ 0,0,0,1 ] ]
  goto_r7:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r7
      pose: [ [ -16,23,0 ], [ 0,0,0,1 ] ]
  goto_r8:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r8
      pose: [ [ -16,31,0 ], [ 0,0,0,1 ] ]
  goto_r9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r9
      pose: [ [ -27,23,0 ], [ 0,0,0,1 ] ]
  goto_r10:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: r10
      pose: [ [ -27,31,0 ], [ 0,0,0,1 ] ]
  goto_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c1
      pose: [ [ -4,1.2,0 ], [ 0,0,0,1 ] ]
  goto_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c2
      pose: [ [ -4,7.37,0 ], [ 0,0,0,1 ] ]
  goto_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c3
      pose: [ [ -4,13.3,0 ], [ 0,0,0,1 ] ]
  goto_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c4
      pose: [ [ -4.8,17.7,0 ], [ 0,0,0,1 ] ]
  goto_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c5
      pose: [ [ -12.5,17.7,0 ], [ 0,0,0,1 ] ]
  goto_c6:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c6
      pose: [ [ -22,17.7,0 ], [ 0,0,0,1 ] ]
  goto_c7:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c7
      pose: [ [ -22,25.3,0 ], [ 0,0,0,1 ] ]
  goto_c8:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c8
      pose: [ [ -22,27.7,0 ], [ 0,0,0,1 ] ]
  goto_c9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -22,35.7,0 ], [ 0,0,0,1 ] ]
  stay:
    type: "stay"
    guard: "1"
    weight: 0.01
  synchronized_transition:
    type: "synchronized_transition"
    guard: "1"
    weight: 0
  pick:
    type: "pick"
    guard: "r2"
    weight: 10
  drop:
    type: "drop"
    guard: "1"
    weight: 10


