# TS definitions are to be interpreted by the agent node. The LTL core planner only uses the node names, connections, weights, and action names to build its automaton.
#
# Possible TS types:
#   3d_pose_region (3D pose [[x,y,z], [x,y,z,w]] with quaternion orientation)
#   2d_pose_region (2D pose [[x,y], phi] with euler angle orientation)
#   3d_point_region (3D point [x, y, z] without orientation)
#   2d_point_region (2D point [x, y] without orientation)
#   turtlebot_load

#state_dim: ["2d_pose_region", "turtlebot_load"]
state_dim: ["2d_pose_region", "A1_load"]
state_models:
  2d_pose_region:
    ts_type: "2d_pose_region"
    initial: "s1"
    nodes:
      p1:
        attr:
          type: "square"
          pose: [[6.8,0], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          p1: "stay"
          c1: "goto_c1_from_p1"
      p2:
        attr:
          type: "square"
          pose: [[7,6], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          p2: "stay"
          c2: "goto_c2_from_p2"
      p3:
        attr:
          type: "square"
          pose: [[6,12], [0]]
          length: 2
          hysteresis: 0.05
        connected_to:
          p3: "stay"
          c3: "goto_c3_from_p3"

      p4:
        attr:
          type: "square"
          pose: [ [ -5.7,0 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          p4: "stay"
          c1: "goto_c1_from_p4"

      p5:
        attr:
          type: "square"
          pose: [ [ -6,6 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          p5: "stay"
          c2: "goto_c2_from_p5"
      p6:
        attr:
          type: "square"
          pose: [ [ -4,12 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          p6: "stay"
          c3: "goto_c3_from_p6"
      c1:
        attr:
          type: "square"
          pose: [ [ 0,0 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c1: "stay"
          p1: "goto_p1_from_c1"
          c2: "goto_c2_from_c1"
          p4: "goto_p4_from_c1"
          c7: "goto_c7_from_c1"
      c2:
        attr:
          type: "square"
          pose: [ [ 0,6 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c1: "goto_c1_from_c2"
          c2: "stay"
          c3: "goto_c3_from_c2"
          p2: "goto_p2_from_c2"
          p5: "goto_p5_from_c2"
      c3:
        attr:
          type: "square"
          pose: [ [ 0,12 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c2: "goto_c2_from_c3"
          c3: "stay"
          c4: "goto_c4_from_c3"
          p3: "goto_p3_from_c3"
          p6: "goto_p6_from_c3"
      c4:
        attr:
          type: "square"
          pose: [ [ 0,17 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c3: "goto_c3_from_c4"
          c4: "stay"
          c5: "goto_c5_from_c4"
      c5:
        attr:
          type: "square"
          pose: [ [ -12,16 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c4: "goto_c4_from_c5"
          c5: "stay"
          c6: "goto_c6_from_c5"
          c8: "goto_c8_from_c5"
          c9: "goto_c9_from_c5"
      c6:
        attr:
          type: "square"
          pose: [ [ -11,-5 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c5: "goto_c5_from_c6"
          c6: "stay"
          c7: "goto_c7_from_c6"
      c7:
        attr:
          type: "square"
          pose: [ [ 0,-5 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c6: "goto_c6_from_c7"
          c7: "stay"
          c1: "goto_c1_from_c7"
      c8:
        attr:
          type: "square"
          pose: [ [ -16.2,15.6 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          s1: "goto_s1_from_c8"
          c8: "stay"
          c9: "goto_c9_from_c8"
          c5: "goto_c5_from_c8"
      c9:
        attr:
          type: "square"
          pose: [ [ -15,21.7 ], [ 0 ] ]
          length: 3
          hysteresis: 0.05
        connected_to:
          c8: "goto_c8_from_c9"
          c9: "stay"
          c10: "goto_c10_from_c9"
          c5: "goto_c5_from_c9"
          x1: "goto_x1_from_c9"
          x2: "goto_x2_from_c9"
      c10:
        attr:
          type: "square"
          pose: [ [ -15,26.8 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c9: "goto_c9_from_c10"
          c10: "stay"
          c11: "goto_c11_from_c10"
          w1: "goto_w1_from_c10"
          w2: "goto_w2_from_c10"
      c11:
        attr:
          type: "square"
          pose: [ [ -15,32 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c10: "goto_c10_from_c11"
          c11: "stay"
          w1: "goto_w1_from_c11"
          w2: "goto_w2_from_c11"
      x1:
        attr:
          type: "square"
          pose: [ [ -19,21 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c9: "goto_c9_from_x1"
          x1: "stay"
      x2:
        attr:
          type: "square"
          pose: [ [ -10,21 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c9: "goto_c9_from_x2"
          x2: "stay"
      w1:
        attr:
          type: "square"
          pose: [ [ -21,29.4 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c10: "goto_c10_from_w1"
          c11: "goto_c11_from_w1"
          w1: "stay"
      w2:
        attr:
          type: "square"
          pose: [ [ -8.2,29 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c10: "goto_c10_from_w2"
          c11: "goto_c11_from_w2"
          w2: "stay"
      s1:
        attr:
          type: "square"
          pose: [ [ -16.58,12 ], [ 0 ] ]
          length: 2
          hysteresis: 0.05
        connected_to:
          c8: "goto_c8_from_s1"
          s1: "stay"

  A1_load:
    ts_type: "A1_load"
    initial: "standby"
    nodes:
      standby:
        connected_to:
          loaded: "pick"
          training: "start_training"
      loaded:
        connected_to:
          standby: "drop"
      training:
        connected_to:
          standby: "terminate_training"
actions:
  goto_p1_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: p1
      pose: [[6.8,0,0], [0,0,-0.707,-0.707]]
  goto_p2_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: p2
      pose: [[7,6,0], [0,0,-0.707,-0.707]]
  goto_p3_from_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: p3
      pose: [[6,12,0], [0,0,-0.707,-0.707]]
  goto_p4_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: p4
      pose: [ [ -5.7,0,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_p5_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: p5
      pose: [ [ -6,6,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_p6_from_c3:
    type: "move"
    weight: 5
    guard: "1"
    attr:
      region: p6
      pose: [ [ -4,12,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_x1_from_c9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: x1
      pose: [ [ -19,21,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_x2_from_c9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: x2
      pose: [ [ -10,21,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_s1_from_c8:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: s1
      pose: [ [ -16.58,12,0 ], [ 0,0,0,1 ] ]
  goto_w1_from_c10:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: w1
      pose: [ [ -21,29.4,0 ], [ 0,0,1,0 ] ]
  goto_w1_from_c11:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: w1
      pose: [ [ -21,29.4,0 ], [ 0,0,1,0 ] ]
  goto_w2_from_c10:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: w2
      pose: [ [ -8.2,29,0 ], [ 0,0,0,1 ] ]
  goto_w2_from_c11:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: w2
      pose: [ [ -8.2,29,0 ], [ 0,0,0,1 ] ]
  goto_c1_from_c7:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c1
      pose: [ [ 0.5,-0.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c1_from_p4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c1
      pose: [ [ -0.5,-0.5,0 ], [ 0,0,0,1 ] ]
  goto_c1_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c1
      pose: [ [ -0.5,0.5,0 ], [ 0,0,-0.707,0.707 ] ]
  goto_c1_from_p1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c1
      pose: [ [ 0.5,0.5,0 ], [ 0,0,1,0 ] ]
  goto_c2_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c2
      pose: [ [ 0.5,5.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c2_from_p5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c2
      pose: [ [ -0.5,5.5,0 ], [ 0,0,0,1 ] ]
  goto_c2_from_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c2
      pose: [ [ -0.5,6.5,0 ], [ 0,0,-0.707,0.707 ] ]
  goto_c2_from_p2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c2
      pose: [ [ 0.5,6.5,0 ], [ 0,0,1,0 ] ]
  goto_c3_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c3
      pose: [ [ 0.5,11.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c3_from_p6:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c3
      pose: [ [ -0.5,11.5,0 ], [ 0,0,0,1 ] ]
  goto_c3_from_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c3
      pose: [ [ -0.5,12.5,0 ], [ 0,0,-0.707,0.707 ] ]
  goto_c3_from_p3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c3
      pose: [ [ 0.5,12.5,0 ], [ 0,0,1,0 ] ]
  goto_c4_from_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c4
      pose: [ [ 0.5,17.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c4_from_c5:
    type: "move"
    weight: 20
    guard: "1"
    attr:
      region: c4
      pose: [ [ -0.5,16.5,0 ], [ 0,0,0,1 ] ]
  goto_c5_from_c6:
    type: "move"
    weight: 40
    guard: "1"
    attr:
      region: c5
      pose: [ [ -11.5,15.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c5_from_c8:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c5
      pose: [ [ -12.5,15.5,0 ], [ 0,0,0,1 ] ]
  goto_c5_from_c9:
    type: "move"
    weight: 15
    guard: "1"
    attr:
      region: c5
      pose: [ [ -12.5,16.5,0 ], [ 0,0.01,0.3127,-0.95 ] ]
  goto_c5_from_c4:
    type: "move"
    weight: 20
    guard: "1"
    attr:
      region: c5
      pose: [ [ -11.5,16.5,0 ], [ 0,0,1,0 ] ]
  goto_c6_from_c5:
    type: "move"
    weight: 40
    guard: "1"
    attr:
      region: c6
      pose: [ [ -11.5,-5.5,0 ], [ 0,0,0.707,-0.707 ] ]
  goto_c6_from_c7:
    type: "move"
    weight: 20
    guard: "1"
    attr:
      region: c6
      pose: [ [ -10.5,-4.5,0 ], [ 0,0,1,0 ] ]
  goto_c7_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c7
      pose: [ [ -0.5,-4.5,0 ], [ 0,0,0.707,-0.707 ] ]
  goto_c7_from_c6:
    type: "move"
    weight: 20
    guard: "1"
    attr:
      region: c7
      pose: [ [ 0.5,-5.5,0 ], [ 0,0,0,1 ] ]
  goto_c8_from_s1:
    type: "move"
    weight: 5
    guard: "1"
    attr:
      region: c8
      pose: [ [ -15.7,15.1,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c8_from_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c8
      pose: [ [ -15.7,16.2,0 ], [ 0,0,1,0 ] ]
  goto_c8_from_c9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c8
      pose: [ [ -16.7,16.2,0 ], [ 0,0,-0.707,0.707 ] ]
  goto_c9_from_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -14,21.2,0 ], [ 0,0,0.707,0.707 ] ]
  goto_c9_from_c8:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -14.5,20.7,0 ], [ 0,0,0.707,0.707 ] ]
  goto_c9_from_x1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -15.5,21.2,0 ], [ 0,0,0,1 ] ]
  goto_c9_from_c10:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -15.5,22.2,0 ], [ 0,0,0.707,-0.707 ] ]
  goto_c9_from_x2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c9
      pose: [ [ -14.5,22.2,0 ], [ 0,0,1,0 ] ]
  goto_c10_from_c9:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c10
      pose: [ [ -14.5,26.3,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c10_from_w1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c10
      pose: [ [ -15.5,26.3,0 ], [ 0,0,0,1 ] ]
  goto_c10_from_c11:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c10
      pose: [ [ -15.5,27.3,0 ], [ 0,0,-0.707,0.707 ] ]
  goto_c10_from_w2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c10
      pose: [ [ -14.5,27.3,0 ], [ 0,0,1,0 ] ]
  goto_c11_from_c10:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c11
      pose: [ [ -14.5,31.5,0 ], [ 0,0,-0.707,-0.707 ] ]
  goto_c11_from_w1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c11
      pose: [ [ -15.5,31.5,0 ], [ 0,0,0,1 ] ]
  goto_c11_from_w2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: c11
      pose: [ [ -14.5,32.5,0 ], [ 0,0,1,0 ] ]
  stay:
    type: "stay"
    guard: "1"
    weight: 0.01
  synchronized_transition:
    type: "stay"
    guard: "1"
    weight: 0
  pick:
    type: "pick"
    guard: "s1"
    weight: 10
  drop:
    type: "drop"
    guard: "1"
    weight: 10
  start_training:
    type: "start_training"
    guard: "c1"
    weight: 10
  terminate_training:
    type: "terminate_training"
    guard: "1"
    weight: 10


